apiVersion: v1
kind: Service
metadata:
  name: arcadebackend
  labels:
    name: arcadebackend    
spec:
  selector:
    name: arcadebackend    
  type: LoadBalancer
  ports:
   - port: 80
     name: arcadebackend
     targetPort: 8080
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadebackend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: arcadebackend 
  minReadySeconds: 5
  strategy:
    type: RollingUpdate 
  template:
    metadata:
      labels:
        name: arcadebackend        
    spec:
      imagePullSecrets:
          - name: pull-secret
      containers:
      - name: arcadebackend
        image: not4uacrc663ad.azurecr.io/gamebot:build1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: arcadebackend         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "8080"
          - name: "PICK_STRATEGY"
            value: "RANDOM"
          - name: "FF_BETS"
            value: "true"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3